name: Bitcoin Watch
favicon: null
layout_spectrum: 0.20614868239499629
typography_spectrum: 0.09349581226706505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.13243031804449856
  lightness: 0.1018616349902004
  saturation: 0.3496842482127249
  rhythmicContrast: 0.02701476006768644
purpose: []
